replicaCount: 1
namespaceOverride: kube-system

nodeSelector:
  kubernetes.io/hostname: node-gpu-01

tolerations:
  - key: nvidia.com/gpu
    operator: Equal
    value: present
    effect: NoSchedule

storageClass:
  create: true
  name: node-gpu-01-local
  provisionerName: rancher.io/node-gpu-01-local
  defaultClass: false
  defaultVolumeType: local
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
  allowedTopologies:
    - matchLabelExpressions:
        - key: kubernetes.io/hostname
          values:
            - node-gpu-01

nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths: []
  - node: node-gpu-01
    paths:
      - /var/mnt/local-storage/local-path-provisioner

configmap:
  helperPod:
    tolerations:
      - key: nvidia.com/gpu
        operator: Equal
        value: present
        effect: NoSchedule
