apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex
  namespace: dex
  labels:
    app.kubernetes.io/name: dex
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
automountServiceAccountToken: false
