apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: strimzi-kafka-operator
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://strimzi.io/charts/
      chart: strimzi-kafka-operator
      targetRevision: 0.50.1
      helm:
        valueFiles:
          - $cluster/kubernetes/overlays/homelab/infrastructure/strimzi-kafka-operator/values.yaml
    - repoURL: https://github.com/Nosmoht/talos-homelab-cluster.git
      targetRevision: main
      path: kubernetes/overlays/homelab/infrastructure/strimzi-kafka-operator/resources
      ref: cluster
    - repoURL: https://github.com/Nosmoht/talos-platform-base.git
      targetRevision: v0.5.0
      ref: base
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
