apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus-cni
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: multus-cni
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  project: infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  sources:
    - repoURL: https://github.com/Nosmoht/talos-platform-base.git
      targetRevision: v0.1.0
      ref: base
    - repoURL: https://github.com/Nosmoht/talos-homelab-cluster.git
      targetRevision: main
      ref: cluster
    - repoURL: https://github.com/Nosmoht/talos-homelab-cluster.git
      targetRevision: main
      path: kubernetes/overlays/homelab/infrastructure/multus-cni/resources
