apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-pki-canary-atlas-svc
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: certificate
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  secretName: vault-pki-canary-atlas-svc-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 720h
  renewBefore: 240h
  issuerRef:
    name: vault-internal
    kind: ClusterIssuer
  dnsNames:
    - atlas-pki-canary.atlas-system.svc.cluster.local
