apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ksops-generator.yaml

resources:
  - cluster-issuer-production.yaml
  - cluster-issuer-staging.yaml
  - cluster-issuer-vault-internal.yaml
  - role-cert-manager-vault-tokenrequest.yaml
  - certificate-vault-pki-canary.yaml
  - certificate-vault-pki-canary-atlas-svc.yaml
