apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myminio-env-configuration
  namespace: minio
  labels:
    app.kubernetes.io/name: myminio-env-configuration
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: SecretStore
  target:
    name: myminio-env-configuration
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    # 1 key: config.env (multi-line .env-format string consumed by MinIO).
    - extract:
        key: clusters/homelab/minio/myminio-env-configuration
