apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: minio
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: secret-store-auth
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
