apiVersion: ENC[AES256_GCM,data:+gs=,iv:Lk7cPouVWmJ3viIBBC+VPNTQqkuP5NMGKr+BYtJ0lx0=,tag:kRvWLMZvME9+Io13w3ei6g==,type:str]
kind: ENC[AES256_GCM,data:HuZRN5ig,iv:vm0Wp9f40IRZ5rKFgr9HTHPYNdNIKGEtA1jGhNTrNrM=,tag:+c8ozmykesk/mLqU4MYFKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uMcGYrmp6aVt037lHq3LtPiTd9zY1ruPRw==,iv:Kn1/dCHhrInEIEOgcyQq4Ljji1UTXCvBCaUcVEYAmfQ=,tag:48xRo1GnK7a4fmwBtT5MkQ==,type:str]
    namespace: ENC[AES256_GCM,data:3yWltD4=,iv:lfA7TLBlBOpShdAs0bX67iPo/vZxxeSI6CFcuy3dnX4=,tag:adp3fgkewxoWOWImEsbwRw==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:DE6zmJo=,iv:fOjGvF6/h3sjcafs56GTBG3lt86d867CfayWlSfUl3Q=,tag:nOPbGPYprhwjE4zig/K3rw==,type:str]
        app.kubernetes.io/instance: ENC[AES256_GCM,data:EO6ju0Hljw==,iv:20eu+UbzqepgS4tbjZTNBeT1yLlmEFbLWaF2vZB/D6U=,tag:z6t+sY9/ZOP8LIlhwek7GA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:qfVV7RB7,iv:tSR167oFzy6iMEUARPmMuEmrq8sQXbJZ5I5EuLJGaco=,tag:Ecbr0dEEYcReEY+zu+eZpQ==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:TbTe9+6GSQ==,iv:aQ00tcLPSh9ElnEx8R4TAN1VDcgBizR7cmFmiJpYavw=,tag:Oe74Ks9TwPO1qQ+u9dn1dQ==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:KhJrZvW3,iv:++YQulSVW9JCY1m/+EuMDiQOwHsUvosg1Nkq2TqLC/o=,tag:nxleHuKhlnK1rY2LXDdfKg==,type:str]
type: ENC[AES256_GCM,data:br7u3Frs,iv:Qq8Q5iZb/U0V8UJWCVxmDPLPONXAItouN9tlM+9/7ak=,tag:hHlZb+bSnbbwOLYs/j5ZIQ==,type:str]
stringData:
    config.env: ENC[AES256_GCM,data:a31ZIvuRnJuR4jWEc69ckBzguMsOPadFKLTxcRThD1YrYsKQGilzO+AmYzQ0gTQSN0dmIMyl/JiX1ZDsOplnnJJtAnYUY6Ik8nr4nwIyrjL5Jmj0ICIkivYShjtvcj/Rnsd7pDnzU0B4eO3MAdbqz2V2n6lRAWhuX9YZk6JiN66r2vrRQA211RIwSTwkmg==,iv:98a5dyQMXs26cemLZAaGNbqRNPhQ2YqvjM9pjzfHh4k=,tag:y9SMzs6mCHZuYyczzPg5Gw==,type:str]
sops:
    age:
        - recipient: age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYnBCb1hBYkpBQnBxcGFx
            enhFdGRlWSt2SlF0Mk9LWklaZjZEN0c2K2tRCldSMWhpS1BaMWpSVDFScldjbzlz
            OVNrUWxXYk5EaU5CZjA1SHlvbWRqYUEKLS0tIEdKd3JMZ1g0MEExUVdLZUgzVjVQ
            eWR4eStKRWJwWmlTSDBBQk5vWDZBak0KaewLLL02QkUXHzB3xOQSY1iHIxuCqOOs
            q7FCYNaw0ckAs40YaJN20lMwmZtOUwy+EMOGVMZsKPSlNFPIv/I9aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T15:38:06Z"
    mac: ENC[AES256_GCM,data:tU6KX2qStzxoV1+GO9GYHjHH57Rho/qwWAwjcJAHEz34kSMHvMH40yQoHenJQpq3YIr9biN8V4fZ4c1yLj45AS3etavV/O5qEFvDhgfiO791c3J+O4p17kzM10p/EgXuuSw9WkL/25rC39KOhTec0iQ4eodSI4XfeNc3hSulfdo=,iv:bjYeQK3JhEouAA3/+BiwjZo5C/e4zVCkjWDfoC14ZVQ=,tag:3pUU+6FGV8vOtDJlSTkCzQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
