# Per-namespace SecretStore for ESO in minio namespace.
# See cert-manager/resources/secret-store.yaml for design rationale.
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-kv
  namespace: minio
  labels:
    app.kubernetes.io/name: vault-kv
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: secret-store
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    vault:
      server: https://vault.vault.svc:8200
      caProvider:
        type: ConfigMap
        name: vault-ca
        key: ca.crt
        namespace: minio
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: eso-minio
          serviceAccountRef:
            name: external-secrets
