apiVersion: redhatcop.redhat.io/v1alpha1
kind: PKISecretEngineRole
metadata:
  name: cert-manager-internal
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: cert-manager-internal
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: vault-pki-role
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  authentication:
    path: kubernetes
    role: vco-pki-admin
    serviceAccount:
      name: controller-manager
  path: pki_int
  allowedDomains:
    - homelab.local
    - svc.cluster.local
  allowBareDomains: true
  allowSubdomains: true
  allowGlobDomains: true
  allowAnyName: false
  requireCn: false
  keyType: ec
  keyBits: 256
  maxTTL: 2160h
