apiVersion: redhatcop.redhat.io/v1alpha1
kind: PKISecretEngineConfig
metadata:
  name: pki-int-config
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: pki-int-config
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: vault-pki-config
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  authentication:
    path: kubernetes
    role: vco-pki-admin
    serviceAccount:
      name: controller-manager
  path: pki_int
  commonName: homelab.local Intermediate CA
  TTL: 43800h
  type: intermediate
  privateKeyType: internal
  keyType: ec
  keyBits: 256
  internalSign:
    name: pki_root
  issuingCertificates:
    - https://vault.vault.svc.cluster.local:8200/v1/pki_int/ca
  CRLDistributionPoints:
    - https://vault.vault.svc.cluster.local:8200/v1/pki_int/crl
