apiVersion: v1
kind: ServiceAccount
metadata:
  name: presync-hook-vault-config-operator
  namespace: vault
  labels:
    app.kubernetes.io/name: presync-hook-vault-config-operator
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: hook-sa
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
