apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: pki-int-mount
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: pki-int-mount
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: vault-secret-engine
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  authentication:
    path: kubernetes
    role: vco-pki-admin
    serviceAccount:
      name: controller-manager
  type: pki
  name: pki_int
  config:
    maxLeaseTTL: "43800h"
