{
 "title": "cert-manager2",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(certmanager_certificate_expiration_timestamp_seconds,namespace)"
    }
   },
   {
    "name": "Certificate",
    "query": {
     "query": "label_values(certmanager_certificate_expiration_timestamp_seconds{namespace=\"$namespace\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Left",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{namespace=~\"$namespace\"} - time()) BY (name,namespace)",
     "legendFormat": " {{namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status) BY (condition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{namespace=~\"$namespace\"} - time()) BY (name,namespace)",
     "legendFormat": " {{namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "ACME Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall requests per 2m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count[2m])) BY (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(certmanager_http_acme_client_request_count)"
      }
     ]
    },
    {
     "title": "/directory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/directory\"}[2m])) BY (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "/acme/cert",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/cert\"}[2m])) BY (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "/acme/new-acct",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/new-acct\"}[2m])) BY (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "/acme/order",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/order\"}[2m])) BY (status)"
      }
     ]
    },
    {
     "title": "/acme/new-order",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/new-order\"}[2m])) BY (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "/acme/authz-v3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/authz-v3\"}[2m])) BY (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "/acme/chall-v3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/chall-v3\"}[2m])) BY (status)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "/acme/finalize",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(certmanager_http_acme_client_request_count{path=\"/acme/finalize\"}[2m])) BY (status)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}