{
 "title": "NVIDIA DCGM Exporter Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "query_result(max by (Hostname) (DCGM_FI_DEV_GPU_UTIL))"
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": "query_result(max by (gpu) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"${hostname:regex}\"}))"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=~\"${hostname:regex}\",gpu=~\"${gpu:regex}\"}",
     "legendFormat": "{{Hostname}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Avg. Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"${hostname:regex}\",gpu=~\"${gpu:regex}\"})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{Hostname=~\"${hostname:regex}\",gpu=~\"${gpu:regex}\"}",
     "legendFormat": "{{Hostname}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"${hostname:regex}\",gpu=~\"${gpu:regex}\"})"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{Hostname=~\"${hostname:regex}\",gpu=~\"${gpu:regex}\"}",
     "legendFormat": "{{Hostname}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_CLOCK{Hostname=~\"${hostname:regex}\",gpu=~\"${gpu:regex}\"}",
     "legendFormat": "{{Hostname}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=~\"${hostname:regex}\",gpu=~\"${gpu:regex}\"}",
     "legendFormat": "{{Hostname}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Mem Cpy Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=~\"${hostname:regex}\",gpu=~\"${gpu:regex}\"}",
     "legendFormat": "{{Hostname}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=~\"${hostname:regex}\",gpu=~\"${gpu:regex}\"}",
     "legendFormat": "{{Hostname}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=~\"${hostname:regex}\",gpu=~\"${gpu:regex}\"}",
     "legendFormat": "{{Hostname}} GPU {{gpu}}"
    }
   ]
  }
 ]
}