apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces-psa.yaml
  - argocd
  - piraeus-operator
  - metrics-server
  - cert-approver
  - cert-manager
  - nvidia-device-plugin
  - nvidia-dcgm-exporter
  - node-feature-discovery
  - gateway-api
  - cloudnative-pg
  - vault-operator
  - vault-config-operator
  - external-secrets
  - redis-operator
  - strimzi-kafka-operator
  - rabbitmq-cluster-operator
  - rabbitmq-messaging-topology-operator
  - rabbitmq-smoke-cluster
  - dex
  - kyverno
  - platform-network-interface
  - local-path-provisioner
  - kube-prometheus-stack
  - loki
  - alloy
  - minio-operator
  - minio
  - multus-cni
  - ingress-front
  - kubevirt
  - kubevirt-cdi
  - tetragon
  - omada-controller
  - pi-public-ingress
