apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: restricted
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: managed
    platform.io/consume.monitoring-scrape: "true"
    platform.io/consume.controlplane-egress: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
  labels:
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: managed
    platform.io/consume.storage-csi: "true"
    platform.io/consume.s3-object: "true"
    platform.io/consume.gateway-backend: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-system
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: managed
    platform.io/consume.monitoring-scrape: "true"
    platform.io/consume.controlplane-egress: "true"
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: strimzi-kafka-operator
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: managed
    platform.io/consume.monitoring-scrape: "true"
    platform.io/consume.controlplane-egress: "true"
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt
  labels:
    app.kubernetes.io/name: kubevirt
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: cdi
  labels:
    app.kubernetes.io/name: cdi
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-operator
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: managed
    platform.io/consume.monitoring-scrape: "true"
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: nvidia-device-plugin
  labels:
    app.kubernetes.io/name: nvidia-device-plugin
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: kagent
  labels:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: managed
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: cilium-secrets
  labels:
    app.kubernetes.io/name: cilium
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    app.kubernetes.io/name: vault-operator
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: managed
    platform.io/consume.monitoring-scrape: "true"
    platform.io/consume.gateway-backend: "true"
    platform.io/consume.controlplane-egress: "true"
    platform.io/consume.vault-secrets: "true"
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: tetragon
  labels:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: omada-controller
  labels:
    app.kubernetes.io/name: omada-controller
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: Namespace
metadata:
  name: public-ingress
  labels:
    app.kubernetes.io/name: pi-public-ingress
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
    platform.io/network-interface-version: v1
    platform.io/network-profile: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest
