apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault.yaml
  - cnp-vault-operator.yaml
  - cnp-vault-ui.yaml
  - servicemonitor-vault.yaml
  - networkpolicy-vault-metrics.yaml
  - networkpolicy-vault-api.yaml
  - rbac-vault-pki-bootstrap.yaml
