apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tls.yaml
  - linstor-cluster.yaml
  - linstor-node-connection.yaml
  - linstor-satellite-configuration.yaml
  - storage-class.yaml
  - storage-class-noreplica.yaml
  - storage-class-vm.yaml
  - storage-pool-autovg.yaml
  - monitoring.yaml
  - cnp-piraeus-operator.yaml
  - cnp-linstor-controller.yaml
  - cnp-linstor-satellite.yaml
  - cnp-ha-controller.yaml
  - cnp-linstor-csi-controller.yaml
  - cnp-linstor-affinity-controller.yaml
  - cnp-linstor-storage-pool-autovg.yaml
