apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: homelab
  namespace: piraeus-datastore
  labels:
    app.kubernetes.io/name: piraeus-datastore
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: linstor-cluster
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  nodeSelector:
    feature.node.kubernetes.io/storage-nvme.present: "true"
  nfsServer:
    enabled: false
  apiTLS:
    certManager:
      kind: Issuer
      name: linstor-api-ca
  internalTLS:
    certManager:
      kind: Issuer
      name: linstor-internal-ca
  controller:
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: NotIn
                      values:
                        - node-03
        containers:
          - name: linstor-controller
            env:
              - name: K8S_AWAIT_ELECTION_LEASE_DURATION
                value: "60"
              - name: K8S_AWAIT_ELECTION_RENEW_DEADLINE
                value: "45"
