apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-gateway
  namespace: default
  annotations:
    argocd.argoproj.io/sync-options: SkipHealthCheck=true
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  gatewayClassName: cilium
  infrastructure:
    parametersRef:
      group: cilium.io
      kind: CiliumGatewayClassConfig
      name: homelab-gateway-config
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.homelab.local"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: homelab-wildcard-tls
      allowedRoutes:
        namespaces:
          from: All
    - name: external-https
      protocol: HTTPS
      port: 443
      hostname: "*.homelab.ntbc.io"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: external-wildcard-tls
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              platform.io/consume.external-gateway-routes: "true"
    - name: internal-trusted-https
      protocol: HTTPS
      port: 443
      hostname: "*.lan.homelab.ntbc.io"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: internal-trusted-wildcard-tls
      allowedRoutes:
        namespaces:
          from: All
