apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-oidc
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: SecretStore
  target:
    name: grafana-oidc
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: clusters/homelab/monitoring/grafana-oidc
