apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-secrets
  namespace: monitoring
  labels:
    app.kubernetes.io/name: oauth2-proxy-secrets
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: external-secret
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-kv
    kind: SecretStore
  target:
    name: oauth2-proxy-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    # 4 keys: prometheus-client-secret, alertmanager-client-secret,
    # prometheus-cookie-secret, alertmanager-cookie-secret.
    - extract:
        key: clusters/homelab/monitoring/oauth2-proxy-secrets
