apiVersion: ENC[AES256_GCM,data:SPg=,iv:bo9ko/bUQ/YlW3eDdy/IryASuWAC2jCUwlwbBM1i3TA=,tag:78Su6WVH0LxTGYtl+L+aVA==,type:str]
kind: ENC[AES256_GCM,data:ZvQ7Cc1e,iv:PeMwLtzjln5pbdiZEvIdHtjyu+bxqw26Ny/i5OmzeA8=,tag:oWdXFdmwblHcXcr+L9dctw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vR/aXxMwaTG4XMm6,iv:hpzLwRsYvUe3wNr3PlJlon0aaPirPYMK0r0gdLnLXGM=,tag:vkGfa9VDhcQw5ksiykR0uw==,type:str]
    namespace: ENC[AES256_GCM,data:okBaOW1YcY6RrQ==,iv:0bm/jKF0Vn5uolEldqZgCehAO3rNXPJKoHNO2EZTldk=,tag:HBXrOFfZp8nslPvJpvVhfQ==,type:str]
stringData:
    client-secret: ENC[AES256_GCM,data:Ruj3aRuJjrOw/bEhVfB2d4HKhJd0rGdlQ+X//gimOj4QzuwRENcyltnKZw==,iv:8LR0Ne991XHrKxke0MN1vCT1irsWykhJJSEF/2asGEM=,tag:ke8w90FHbWdx5PCmYI7NsQ==,type:str]
sops:
    age:
        - recipient: age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NEx0ME0wZHVWTmNJYTlD
            a1ZsQmpTT0hjN0h6SkNwWUNoSGJkZ3hvc1VNCkV3Mit2em96ekJEbnpVNis0WG9F
            eng4VzN5R0d0VG01aGVMQXdBTnZJZHcKLS0tIHltZ1ZwRnJKZ3B0Vmk5K0M4cjFr
            V3BOU0NKaDZ1S2g3OXdISEhuS2VOOUUK1dRljEa081SET24vNAWHcdCb0ByC8es7
            g5qCoDG5cJLhm4nLuiOLV+l+VBRFyO0OE0PE96LEmQBHezDup7EHbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T08:59:39Z"
    mac: ENC[AES256_GCM,data:WUwJ40UUFVDFMIbVe0audaSP9zRWfx/5PmRh7Kkm/72lR/3eZS6WGLk+QUuHulthmVxgIcenZWie1T9A6HwT0TU6HSQjWCY9JfKwn81If7ZrrGesa4JDZDU/iKwDDcAAAzWfvakcDnfQKpaJDSNLMoIHDRkX+7m/boJUNzC7P08=,iv:J2/tbu+rhTW8aM3jE0vk+GugiLQ7Nv4cIlQWW5pvyKk=,tag:9nY4FOYMypFu8vbHbQICIw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
