apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: grafana-oidc-secret
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - grafana-oidc-secret.sops.yaml
