apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-allowed-emails
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: oauth2-proxy
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
data:
  allowed-emails: |
    nosmoht
