apiVersion: ENC[AES256_GCM,data:6uE=,iv:VSFO0Ze8UMcHs6Ylgq3SPWbb4MjwxV5ZCuxv9vsOa8M=,tag:ljd4lweHQRHmdBjnuo032w==,type:str]
kind: ENC[AES256_GCM,data:q4ZwKbit,iv:pLmNJ7bSaDJJeTBfrhszDOwMnzdycRkjyr3YIk1pQk0=,tag:vEABFa+YuZvyTNZszdHlsw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8BrAqTf2RKwgvOoOyAYotBoCx34=,iv:nlZpCBN7KPNyZCbeNzWHEP9S/E3n5el1amdpk1Ajup8=,tag:1LI2XmW/C2j95qBcPOrONA==,type:str]
    namespace: ENC[AES256_GCM,data:rU1jQW75l7KQ4Q==,iv:0Xi7Rs5df4L6RSJrCLgZlNdmyGB0X9gHRHYZei56Sv8=,tag:GiJncWbmPpVcf984l2Xeqw==,type:str]
type: ENC[AES256_GCM,data:eQSQv2xz,iv:MLd+Ltr+LLwNEAtEeSkcnUH9NKDrp8NaIoABqDDOr5E=,tag:+at9My1gDcpdGAIi+FI6hg==,type:str]
stringData:
    prometheus-client-secret: ENC[AES256_GCM,data:3xgVcjWoskA7bJJ+tqX8TnHPecK8R3Ay33Ua94lJ/aUB7wM1W87eZlupXdzM+QtiFZ8dj9BegX7/dXBsOw7esw==,iv:imQe5PmRSwfAUvyn3vZdNw1/SxHX8On6uadER3OqgxA=,tag:F2HpbXcMr48yzrJZ+XNKcQ==,type:str]
    alertmanager-client-secret: ENC[AES256_GCM,data:fdBC6KWKIei9gRKFs5GKa8fztI40r3fLzh04/bIHGVlbCcUdI/bNP9F9ediAwkw6P5YZGYRshjQQUb4jtb6f4A==,iv:9P5zPh+2OpFi8TeBn5bxM8n+DBeGAvW6T1MAONN+ylI=,tag:ZcR8d7PO/rmW23hD7C0V/w==,type:str]
    prometheus-cookie-secret: ENC[AES256_GCM,data:QmiN34ExHET/doZ4XY52stFY4+rGZFVicmopdbI+9O0=,iv:TFs5H944lipjW1Bv/WwmH0LeypRYJ7h6Fdf7rZb/mAo=,tag:ar2tmTTl2EH3bbMHEeMp0Q==,type:str]
    alertmanager-cookie-secret: ENC[AES256_GCM,data:EJSaYYQhNejLwyrParu1V8ynrZHtYeinL4nnpGW5M88=,iv:cCbdLTNeH+KILNIkm4xp/FaCrW/dlbRMdNCr6hBSm6Y=,tag:NYqQEF2qMi3S/Krl8SdGRg==,type:str]
sops:
    age:
        - recipient: age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaHU4bEUwVXFBOGQ3b096
            d0lCbUhzeVk4aW4xQlprSVk3anlJcklzbmpzCjhFTy93Rk1NYU9RSDFxbUJIdktZ
            aGVnRlJPSGpuUFlOWklKbjVQUXpvaG8KLS0tIFlzNHJXMFJFTnFjVE00a2grT2t4
            dmoxZW1TbzZwWm9BcFNhTGl1b2VneG8KNuQxGXekdBONrjcIfChGa5zBeeEN19DM
            wei157VmdLCuo/zY8IGHVCpcLPoX19NDv6WtyKeTLMuT26KTZBa6DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T08:59:41Z"
    mac: ENC[AES256_GCM,data:VpIVxlv7vhGOZH1h9+fI5ByGHwtMb90wMa9x0CGKS72e1GTlFygTh/YDMdjPnJJvNt9MS+LTvDfrtzFokDhWUuXAArkhF/MUN3OkZM7sgrDVpBpcz6Kx0jSD9ocDIblItm71mZ6P0m7xfjwg1jKqCxPDcxnGhhtYexVptgkutSg=,iv:hdv84UhcNvYZZ3uCEjKnGvIuck9UrexJinAhAR5JUOs=,tag:aS63hRYKb28jB5GCfMl/qw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
