apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: presync-hook-kube-prometheus-stack
  namespace: monitoring
  labels:
    app.kubernetes.io/name: presync-hook-kube-prometheus-stack
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: hook-rbac
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: presync-hook-kube-prometheus-stack
  namespace: monitoring
  labels:
    app.kubernetes.io/name: presync-hook-kube-prometheus-stack
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: hook-rbac
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: presync-hook-kube-prometheus-stack
subjects:
  - kind: ServiceAccount
    name: presync-hook-kube-prometheus-stack
    namespace: monitoring
