apiVersion: ENC[AES256_GCM,data:8bM=,iv:XyQlP9smbEJGt1HgqmVE+ncjxObe9jny9QnddTck60A=,tag:SqHFOyIHNWC+CZ/+qCqW7Q==,type:str]
kind: ENC[AES256_GCM,data:azyKkuH6,iv:NHtq+V5G/iqSEHu2kVrRsotO5lSF4Ka4zplhIXj9tjI=,tag:WcGdlT2k+k8Gi/+3K4earw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dZvkVr362UUJ+U7i3BfTUA99Z5vFWg==,iv:OJn2rSc1DFDm+nwOcz7VdBh/1zeATbHxB2eoBJB9wP0=,tag:kwNN5TirRQmSrZO5XRIQMg==,type:str]
    namespace: ENC[AES256_GCM,data:BLnR/kaH3aplqg==,iv:dD6Eut4SDejRUbkvvJbFv6w+ppF1BSecGj3SUerk8vM=,tag:66YGav3ds8MUCBODA33VQA==,type:str]
type: ENC[AES256_GCM,data:uLMKat93,iv:67w7lJL1xLpkZrRUoLHWwq8iGSai5TyhmO37RBm2UMw=,tag:SHQELl2+qFyxIvbVwxPNjw==,type:str]
stringData:
    LOKI_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:HcT7GXjH6VMClsZvNg==,iv:tRLwpMowXwRcm9VmlzmlIszOtUvoo9alld/7M2TZVSo=,tag:tTwoh15i+ZlE24a8wniTMg==,type:str]
    LOKI_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oqM/GjjOsZ/yyJDz48UotIMJlNaTBRPViNns5oumlIWLl4tdNafolAD8fqVfqz9s,iv:YRNDIN+PFxrrUQrt53Bo9Y9Vtih4/f7HrhSPu6X2Hiw=,tag:1P9vQQxzM1NGc0POjP0YdA==,type:str]
sops:
    age:
        - recipient: age1t7jy2m2pqwnwfhx0dk85trhw9aae9qln9ng6m4tgy47jk3ngr93spv0hsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdURBYkRIZG5Ba1hCbHpn
            SFUvcnU2Z0pESnV6cncwUlV4L2EvMmtDbDFRCkpwdncvakN4NklpU0tYK1UwQTcy
            QVU5bXRwYjh6d3FGM1F4cWU1M0lrMkEKLS0tIHM3ZWtiNGhObkc0eUJ0OW1lSHhj
            ek1PMmwyQkxaeklSdEJqSCtxZHhyaWsKCoGNmrwcz2XoHw2689x3JHnARRqxMQNS
            CYXD20kkLU4fUjShbyEDoo35IBzdNUW3UmnHuvtpzHszZjkuyOwPLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T17:08:40Z"
    mac: ENC[AES256_GCM,data:WRmE6nW0zHsRGgQseyG3nB7SKt2Dpr7pL9oFAAfFEJhX9JC11vnW8LIxkGLqNRIb36V/k5LyC59u7r1cwcrDtuuI8yiMo7F4QvVWL1+1QapGNVq/rn5V0B3o83zGhMrkcRmOYYlvkdg/ld99GcXw6ohMf6QXG3roS6rC1TDOPXk=,iv:UIHzFFPXOa4o5IVpIwOOs7Ei6hQLAvUv/EtGAM9D3Kk=,tag:CUvS2CHfgsMw4uFjeFmcpA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
