apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tracingpolicy-process-exec.yaml
  - tracingpolicy-file-access.yaml
  - tracingpolicy-network-connect.yaml
  - grafana-dashboard.yaml
