apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-config-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: vault-config-operator
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://redhat-cop.github.io/vault-config-operator
      chart: vault-config-operator
      targetRevision: v0.8.38
      helm:
        valueFiles:
          - $base/kubernetes/base/infrastructure/vault-config-operator/values.yaml
    - repoURL: https://github.com/Nosmoht/talos-homelab-cluster.git
      targetRevision: main
      path: kubernetes/overlays/homelab/infrastructure/vault-config-operator/resources
      ref: cluster
    - repoURL: https://github.com/Nosmoht/talos-platform-base.git
      targetRevision: v0.1.0
      ref: base
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
