apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: project
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  description: User-facing applications
  sourceRepos:
    - https://github.com/Nosmoht/Talos-Homelab.git
    - https://github.com/Nosmoht/talos-platform-base.git
    - https://github.com/Nosmoht/talos-homelab-cluster.git
  destinations:
    - namespace: apps-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
