apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.0.1
      helm:
        valueFiles:
          - $base/kubernetes/base/infrastructure/external-secrets/values.yaml
    - repoURL: https://github.com/Nosmoht/talos-homelab-cluster.git
      targetRevision: main
      ref: cluster
      helm:
        valueFiles: []
    - repoURL: https://github.com/Nosmoht/talos-platform-base.git
      targetRevision: v0.1.0
      ref: base
      helm:
        valueFiles: []
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
