apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/instance: homelab
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: homelab
    app.kubernetes.io/managed-by: argocd
spec:
  project: infrastructure
  sources:
    - repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      targetRevision: 0.17.4
      helm:
        valueFiles:
          - $base/kubernetes/base/infrastructure/node-feature-discovery/values.yaml
    - repoURL: https://github.com/Nosmoht/talos-homelab-cluster.git
      targetRevision: main
      path: kubernetes/overlays/homelab/infrastructure/node-feature-discovery/resources
      ref: cluster
    - repoURL: https://github.com/Nosmoht/talos-platform-base.git
      targetRevision: v0.1.0
      ref: base
  destination:
    server: https://kubernetes.default.svc
    namespace: node-feature-discovery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
