# Top-level overlay entry — consumed by App-of-Apps.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application-crds.yaml
  - application.yaml
  - application-config.yaml
